---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scheduling.codeacme.org
  resources:
  - snoozewindows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scheduling.codeacme.org
  resources:
  - snoozewindows/finalizers
  verbs:
  - update
- apiGroups:
  - scheduling.codeacme.org
  resources:
  - snoozewindows/status
  verbs:
  - get
  - patch
  - update
