# This rule is not used by the project kube-snooze itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the scheduling.codeacme.org.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kube-snooze
    app.kubernetes.io/managed-by: kustomize
  name: snoozewindow-editor-role
rules:
- apiGroups:
  - scheduling.codeacme.org
  resources:
  - snoozewindows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scheduling.codeacme.org
  resources:
  - snoozewindows/status
  verbs:
  - get
