apiVersion: scheduling.codeacme.org/v1alpha1
kind: SnoozeWindow
metadata:
  name: simple-snooze
  namespace: default
spec:
  labelSelector:
    app: "test-app"
  
  snoozeSchedule:
    cronExpression: "0 22 * * *"  # Every day at 10 PM
  
  wakeSchedule:
    cronExpression: "0 8 * * *"   # Every day at 8 AM
  
  timezone: "UTC"
  
  resourceTypes:
    - kind: "Deployment"
      apiVersion: "apps/v1"
      scaleToZero: true
  
  snoozeAction:
    scaleToZero: true
  
  backupConfig:
    storeInAnnotations: true
---
# Simple test deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  namespace: default
  labels:
    app: "test-app"
  annotations:
    kube-snooze/enabled: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "test-app"
  template:
    metadata:
      labels:
        app: "test-app"
    spec:
      containers:
      - name: app
        image: nginx:latest
        ports:
        - containerPort: 80 