apiVersion: scheduling.codeacme.org/v1alpha1
kind: SnoozeWindow
metadata:
  name: simple-snooze
  namespace: default
spec:
  labelSelector:
    app: "test-app"
  
  snoozeSchedule:
    cronExpression: "0 22 * * *"  # Every day at 10 PM
  
  wakeSchedule:
    cronExpression: "0 8 * * *"   # Every day at 8 AM
  
  timezone: "UTC"
  
  resourceTypes:
    - kind: "Deployment"
      apiVersion: "apps/v1"
      scaleToZero: true
  
  snoozeAction:
    scaleToZero: true
  
  backupConfig:
    storeInAnnotations: true 