apiVersion: scheduling.codeacme.org/v1alpha1
kind: SnoozeWindow
metadata:
  name: snooze-nginx
  namespace: kube-snooze-system
spec:
  labelSelector:
    kube-snooze/enabled: "true"
  snoozeSchedule:
    startTime: "6:20"
    endTime: "6:25"
    date: "2025-07-20"
  timezone: "UTC"

# Simple test deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  namespace: kube-snooze-system
  labels:
    app: "test-app"
    kube-snooze/enabled: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "test-app"
  template:
    metadata:
      labels:
        app: "test-app"
    spec:
      containers:
      - name: app
        image: nginx:latest
        ports:
        - containerPort: 80 
